### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by glsf91** [hberntsen/mhi-ac-ctrl-esp32-c3#1]
The code with the example is not compiling.
It is complaining about restore_mode in the yaml file.
Without restore_mode I get an error:
src/mhi_ac_ctrl.h:98:36: error: 'class MhiActiveModeSwitch' has no member named 'get_initial_state_with_restore_mode'
         bool initial_state = this->get_initial_state_with_restore_mode().value_or(true);

**Comment by hberntsen** [comment]
Which version of esphome are you using?

**Comment by glsf91** [comment]
That was indeed the problem. I thought I updated esphome but because an older python version the version was much lower.
Now updated everything and compiling fine.
My apologies.
