### ISSUE TITLE
Need to fix some errors

### ISSUE THREAD

**Issue by MrC0nst** [hberntsen/mhi-ac-ctrl-esp32-c3#4]
Dear Harm Berntsen,

Could you please fix some errors?
https://github.com/hberntsen/mhi-ac-ctrl-esp32-c3/blob/e68566512c19821c9d168f607f340032cf7778da/esphome/my_components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp#L62 **GPIO_NUM_9** need to be replaced with **GPIO_CS_OUT**
same for https://github.com/hberntsen/mhi-ac-ctrl-esp32-c3/blob/e68566512c19821c9d168f607f340032cf7778da/esphome/my_components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp#L72

What **GPIO_NUM_3** is used for?
https://github.com/hberntsen/mhi-ac-ctrl-esp32-c3/blob/e68566512c19821c9d168f607f340032cf7778da/esphome/my_components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp#L399

Thanks in advance.

**Comment by hberntsen** [comment]
GPIO 3 is the Red LED on the board, see https://docs.ai-thinker.com/_media/esp32/docs/esp-c3-32s-kit-v1.0_specification.pdf . It was nice during development but not really needed now. I'll get rid of it

**Comment by hberntsen** [comment]
I've fixed these issues :)!
